# Generated by Django 3.1.4 on 2021-01-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
