# Generated by Django 3.1.4 on 2021-01-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_App', '0002_quiz_questions_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
