# Generated by Django 3.1.4 on 2021-03-04 10:03
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_auto_20210219_1326'),
    ]

    operations = [
        UnaccentExtension()
    ]
