# Generated by Django 3.1.4 on 2021-01-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_App', '0003_auto_20210106_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions_number',
        ),
    ]
