# Generated by Django 3.1.4 on 2021-02-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_App', '0004_remove_quiz_questions_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='Quiz', max_length=250),
        ),
    ]
