# Generated by Django 3.1.4 on 2021-02-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_App', '0006_quiz_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='language',
            field=models.CharField(default='fr', max_length=2),
            preserve_default=False,
        ),
    ]
